[86bybn1q6][drag-and-drop] keyboard navigation and several minor fixes
semrush/intergalactic pull request #1316
Opened 2024-04-22 10:36 UTC by msereniti

## Motivation and Context

This PR fixes a11y issues with DragAndDrop component:
1. [x] Select looses highlight after drag and drop
1. [x] Tabline styles are broken
1. [x] Tabline items swap glitch
1. [x] Dropdonzes outline style
1. [x] Dropzone is draggable from keyboard 
1. [x] Arrows navigation not working
1. [x] In grids arrow up navigates to the prev item instead of one on the top
1. [x] Wrong VO announced positions
1. [x] Weird examples

## How has this been tested?

Manually with added examples.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [x] Nice improve.

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly or it's not required.
- [x] Unit tests are not broken.
- [x] I have added changelog note to corresponding `CHANGELOG.md` file with planned publish date.
- [ ] I have added new unit tests on added of fixed functionality.

2024-04-22 13:42 UTC, sheila-semrush commented
1. It's wrong behaviour that the dragged item is swapped with the item which "place it takes". Items shouldn't swap places, dragged item should be dropped between other items, and these other items shouldn't change order.
2. Would be nice to have at least one example using `zoneName`. We could add `zoneName` to the example with cards, or make a separate example with it.

2024-04-22 16:28 UTC, sheila-semrush requested changes
1. It's wrong behaviour that the dragged item is swapped with the item which "place it takes". Items shouldn't swap places, dragged item should be dropped between other items, and these other items shouldn't change order.
2. Would be nice to have at least one example using zoneName. We could add zoneName to the example with cards, or make a separate example with it.
3. Dragged element becomes gray only after changing position, it should become gray as soon as it's grabbed (or never)
<img width="335" alt="image" src="https://github.com/semrush/intergalactic/assets/166654065/84d984c3-242b-47c5-9d71-fb7a58105700">

2024-04-25 10:21 UTC, ilyabrower commented on semcore/drag-and-drop/src/style/drag-and-drop.shadow.css
> +  /* padding-top: var(--intergalactic-spacing-4x, 16px); */
remove or uncomment

2024-04-25 10:22 UTC, ilyabrower commented on semcore/drag-and-drop/src/style/drag-and-drop.shadow.css
> +  /* padding-left: var(--intergalactic-spacing-4x, 16px); */
and this

2024-04-25 10:23 UTC, ilyabrower commented on website/docs/.vitepress/theme/style.css
> +  /* overflow: auto; */
?

2024-04-26 16:04 UTC, ilyabrower commented on semcore/drag-and-drop/src/DragAndDrop.tsx
> +          this.state.items[dragOver as any]?.node.focus();
are you sure about `as any` ? looks like we could use `number` as array index

2024-04-26 16:05 UTC, ilyabrower approved these changes

2024-04-26 18:26 UTC, merged