[86bzcjrc6][website] Fix filters serp typo
semrush/intergalactic pull request #1485
Opened 2024-07-02 11:59 UTC by ilyabrower

2024-07-03 18:01 UTC, msereniti approved these changes

2024-07-04 13:48 UTC, sheila-semrush requested changes
all good, only there's an unnecessary 4px gap between the "select all" item and the list 
<img width="351" alt="image" src="https://github.com/semrush/intergalactic/assets/166654065/ae44efb5-5292-4fa4-beb2-6891c7fcb7b9">

2024-07-05 09:00 UTC, ilyabrower commented
> all good, only there's an unnecessary 4px gap between the "select all" item and the list 

fixed

2024-07-05 10:52 UTC, sheila-semrush approved these changes

2024-07-05 13:41 UTC, merged