[86bze05tk][input-tags] a11y enhance
semrush/intergalactic pull request #1541
Opened 2024-07-22 20:45 UTC by msereniti

## Motivation and Context

This PR fixes a11y of InputTags component and also contains a several fixes for Tag component.

## How has this been tested?

Manually with VO and with existing tests.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [x] Nice improve.

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly or it's not required.
- [x] Unit tests are not broken.
- [x] I have added changelog note to corresponding `CHANGELOG.md` file with planned publish date.
- [ ] I have added new unit tests on added of fixed functionality.

2024-07-23 04:51 UTC, ilyabrower reviewed
The code is ok, but check the regenerated snapshots

2024-07-25 20:20 UTC, sheila-semrush requested changes
Found several medium/minor issues, DMd in Slack.

2024-08-19 15:59 UTC, sheila-semrush requested changes
Found 2 issues:

1. Addon has incorrect position:
<img width="767" alt="image" src="https://github.com/user-attachments/assets/83719282-9f8a-4db7-a1d4-c321d724a29e">

#

2. Circle is invisible:
<img width="739" alt="image" src="https://github.com/user-attachments/assets/0489b235-653c-415f-be1f-92092beb66a8">

2024-09-12 17:53 UTC, sheila-semrush approved these changes
From my side everything is ok.
@j-mnizhek can you review the docs?
This component doesn't have its own a11y props, everything comes from the children components. So I just updated the keyboard interaction table, and fixed some things in the Design guide.

2024-09-13 14:57 UTC, j-mnizhek approved these changes
Looks good!

I only updated content in our examples a little bit, updated and added placeholders. And also used the same text for the Accessibility documentation as we use for the Input component.

2024-09-13 16:47 UTC, msereniti commented on semcore/input-tags/src/InputTags.tsx
> +        <Portal>
I need to place this node somewhere, to apply description (aria-descibedby works, aria-description doesn't). I don't want to put this description as node before the place it's applied

2024-09-13 16:48 UTC, msereniti commented on semcore/tag/src/style/tag.shadow.css
> +} */
Removed

2024-09-13 16:49 UTC, msereniti commented on semcore/tag/src/Tag.jsx
> +  return sstyled(styles)(<SCircle render={Box} tag='span' tag-color={resolveColor(color)} />);
Added

2024-09-13 16:50 UTC, msereniti commented on semcore/input-tags/__tests__/__image_snapshots__/inputtags-renders-different-sizes.png
Fixed

2024-09-13 16:50 UTC, msereniti commented on semcore/input-tags/src/InputTags.tsx
> +  const interactive = props.ediable || props.onClick;
Fixed

2024-09-13 16:50 UTC, msereniti commented on semcore/input-tags/src/InputTags.tsx
> +      {true && (
Removed

2024-09-13 16:53 UTC, msereniti commented on semcore/tag/__tests__/__image_snapshots__/tagcontainer-should-support-active.png
I see this one pixel change only in this test 🤷

2024-09-16 10:31 UTC, j-mnizhek commented
Sorry, folks, I've just noticed that something strange happened with Tag's inner paddings in the playground. They have become bigger.

In this branch:
<img width="750" alt="image" src="https://github.com/user-attachments/assets/234bbd8f-ad00-4811-88da-202c06bacbf6">
<img width="743" alt="image" src="https://github.com/user-attachments/assets/0411cb58-a742-4639-a453-17c756eca50c">

In the master branch (how it should be):
<img width="728" alt="image" src="https://github.com/user-attachments/assets/ef533a7f-da3a-4a75-b1f5-2948e29fb879">
<img width="736" alt="image" src="https://github.com/user-attachments/assets/804ed264-4663-4562-a497-0f48a1761229">

2024-09-18 10:52 UTC, merged