[86bzn2n53][docs] moved dos-donts table into separated vue component
semrush/intergalactic pull request #1550
Opened 2024-07-28 20:29 UTC by msereniti

## Motivation and Context

This component should be very reusable. Also I've fixed how to looks like in production.

## How has this been tested?

Manually.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [x] Nice improve.

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly or it's not required.
- [x] Unit tests are not broken.
- [x] I have added changelog note to corresponding `CHANGELOG.md` file with planned publish date.
- [ ] I have added new unit tests on added of fixed functionality.

2024-07-29 05:43 UTC, ilyabrower approved these changes

2024-08-02 16:46 UTC, sheila-semrush requested changes
need to add the props to pass the content 
(adding this comment now so that the PR status is clear)

2024-08-05 11:03 UTC, sheila-semrush requested changes
Almost all good, only one improvement needed.
A lot of tables have width less than 100%, we need to make the content stretch to 100% as well.
(I made a commit, if you pull it, you'll see examples of tables where content is narrow.)
<img width="785" alt="image" src="https://github.com/user-attachments/assets/e2931837-4c82-4067-a290-5e0f53059d17">

2024-08-07 17:42 UTC, sheila-semrush approved these changes
thanks, looks great!

2024-08-07 17:42 UTC, merged