[86bydf2fy][dropdown-menu] a11y improvements
semrush/intergalactic pull request #1617
Opened 2024-08-23 09:19 UTC by ilyabrower

## Motivation and Context

## How has this been tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Nice improve.

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly or it's not required.
- [ ] Unit tests are not broken.
- [ ] I have added changelog note to corresponding `CHANGELOG.md` file with planned publish date.
- [ ] I have added new unit tests on added of fixed functionality.

2024-09-03 16:28 UTC, j-mnizhek approved these changes
Updated a11y documentation for DropdownMenu.

@sheila-semrush Sheila, please take a look at the updated accessibility documenation for DropdownMenu 🙏

2024-09-03 16:50 UTC, j-mnizhek commented
I have a couple of questions:
1. Should we add documentation for `DropdownMenu.Item.Content` and `DropdownMenu.Group` to the API page?

2. Can we center ChevronRight icon a little bit? Now it looks a little bit higher than it was.

**Current:**
<img width="329" alt="image" src="https://github.com/user-attachments/assets/08374868-baea-4d42-9260-d8d9880c0438">

**Before:**
<img width="431" alt="image" src="https://github.com/user-attachments/assets/4db8025d-e56f-4406-a644-f2f8a3ae0004">

2024-09-04 10:36 UTC, j-mnizhek commented
I've just added:

1. Styles for Button with S size, so we can use such a small Button for the cases when we need these kind of an interactive addons inside some other components when there is not much space.
![image](https://github.com/user-attachments/assets/43480638-e881-46f6-acea-78d82558a8d0)

2. New token for S sized controls with 20px height.

_Now I'm updating some illustrations for the design guide, will push them a little bit later._

2024-09-04 15:58 UTC, sheila-semrush requested changes
Left a few comments

2024-09-04 16:58 UTC, j-mnizhek commented on website/docs/components/dropdown-menu/dropdown-menu-a11y.md
> +| `DropdownMenu.Item.Hint`                         | `aria-hidden="true"`         | Hides element from assistive technologies.
I see that Iliia has updated documentation in the API doc, finally. There were some old names, I'll fix to the new ones of course ❤️

2024-09-04 17:09 UTC, j-mnizhek commented on website/docs/components/dropdown-menu/dropdown-menu.md
Yesss! Was thinking about it too, actually ❤️

2024-09-04 17:16 UTC, j-mnizhek commented on website/docs/components/dropdown-menu/dropdown-menu-a11y.md
> +| `DropdownMenu.Item.Content`                      | `aria-haspopup="dialog"`     | Indicates that the element triggers a dialog.
These components are not only for the nested menus, so I guess it's okay to leave them without this additional comment.

2024-09-05 13:20 UTC, sheila-semrush commented on website/docs/components/dropdown-menu/dropdown-menu-a11y.md
> +| `DropdownMenu.Item.Content`                      | `aria-haspopup="dialog"`     | Indicates that the element triggers a dialog.
but the descriptions relate to the properties, not to the components. Current description can make an impression that the property is always there

2024-09-05 15:21 UTC, sheila-semrush requested changes
@ilyabrower I've made 2 commits, 1st with some cosmetic documentation changes, and 2nd replacing most triggers with simple buttons. I think they're more appropriate for our examples given that we don't want to show changing content in the triggers. (Julia agreed)

There's one bug left, with menu not closing on ESC when a list item with nested controls is selected.

2024-09-05 19:47 UTC, ilyabrower commented
> @ilyabrower I've made 2 commits, 1st with some cosmetic documentation changes, and 2nd replacing most triggers with simple buttons. I think they're more appropriate for our examples given that we don't want to show changing content in the triggers. (Julia agreed)
> 
> There's one bug left, with menu not closing on ESC when a list item with nested controls is selected.

I fixed bug with ESC

2024-09-06 10:25 UTC, sheila-semrush approved these changes
Works great!

2024-09-06 18:00 UTC, msereniti approved these changes

2024-09-06 19:16 UTC, merged