[86c04hbeu][data-table] data table sort column properties
semrush/intergalactic pull request #1636
Opened 2024-09-04 13:33 UTC by ilyabrower

## Motivation and Context
I've disabled changing sorting columns width by default.
I've added `changeSortSize` to enable this logic on columns and `sortSizeRecalculation` to set by which columns we should recalculate width of table. By default we using column width maximum width.

## How has this been tested?
Manually

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [X] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Nice improve.

## Checklist:

- [X] My code follows the code style of this project.
- [X] I have updated the documentation accordingly or it's not required.
- [X] Unit tests are not broken.
- [X] I have added changelog note to corresponding `CHANGELOG.md` file with planned publish date.
- [ ] I have added new unit tests on added of fixed functionality.

2024-09-05 11:50 UTC, sheila-semrush requested changes
1. A line break in the "KD, %" column appeared in Firefox:
<img width="725" alt="image" src="https://github.com/user-attachments/assets/8e8fffb7-a2cd-4d17-b1a1-b44b945ca1f4">

#

2. Also discussed to slightly change the examples: make the "Vol" column noticeably smaller than "Keyword", and in the last example assign the sortSizeRecalculation prop to the "Vol", so it's obvious that we can take space from a column that's not the largest.

2024-09-06 08:10 UTC, ilyabrower commented
> 1. A line break in the "KD, %" column appeared in Firefox:
> 
> <img alt="image" width="725" src="https://private-user-images.githubusercontent.com/166654065/364762870-8e8fffb7-a2cd-4d17-b1a1-b44b945ca1f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MTA1MjksIm5iZiI6MTcyNTYxMDIyOSwicGF0aCI6Ii8xNjY2NTQwNjUvMzY0NzYyODcwLThlOGZmZmI3LWEyY2QtNGQxNy1iMWExLWI0NGI5NDVjYTFmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQwODEwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWJmODJjNDY3NmYxN2U5MWVlZDBhNWM4OWZkZTFkMjc2ZjA0MzhkNDg3YmZjOGJjZDgxZWE2ODQ1OWRlMjMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bRL3MrQPgQLr7iWXFCOEwK8NQESUJEsO2gKKNvoOpSQ">
> 2. Also discussed to slightly change the examples: make the "Vol" column noticeably smaller than "Keyword", and in the last example assign the sortSizeRecalculation prop to the "Vol", so it's obvious that we can take space from a column that's not the largest.

Fixed the first one and changed examples

2024-09-06 10:30 UTC, sheila-semrush approved these changes
All good!

2024-09-06 19:19 UTC, msereniti approved these changes

2024-09-06 19:20 UTC, merged