[86c0ag8xw] Update ButtonLink playground
semrush/intergalactic pull request #1650
Opened 2024-09-16 13:56 UTC by sheila-semrush

## Motivation and Context

- Added posibility to see the ButtonLink component in the Button playground
- Added logic to show only relevant props depending on the chosen component
- Fixed size labels for Link (they had outdated font sizes in px)
- Added logic to show Icon with size=L when font size > 300

## How has this been tested?

Manually.

## Screenshots (if appropriate):

<img width="733" alt="image" src="https://github.com/user-attachments/assets/607f64ec-dc27-45e7-8a3e-605b8e8cd1c9">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [x] Nice improve.

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly or it's not required.
- [ ] Unit tests are not broken.
- [ ] I have added changelog note to corresponding `CHANGELOG.md` file with planned publish date.
- [ ] I have added new unit tests on added of fixed functionality.

2024-09-17 10:59 UTC, ilyabrower requested changes

2024-09-17 10:59 UTC, ilyabrower commented on website/docs/components/button/button.md
> +      // defaultValue: THEME["secondary"][1],
let's remove unused item

2024-09-17 13:43 UTC, sheila-semrush commented on website/docs/components/button/button.md
> +      // defaultValue: THEME["secondary"][1],
done

2024-09-20 14:04 UTC, ilyabrower approved these changes

2024-09-20 14:04 UTC, merged