[UIK-2426][bulk-textarea] new bulk textarea component
semrush/intergalactic pull request #1893
Opened 2024-12-23 13:16 UTC by ilyabrower

## Motivation and Context

## How has this been tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Nice improve.

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly or it's not required.
- [ ] Unit tests are not broken.
- [ ] I have added changelog note to corresponding `CHANGELOG.md` file with planned publish date.
- [ ] I have added new unit tests on added of fixed functionality.

2025-01-16 14:40 UTC, j-mnizhek requested changes
Added updates for texts from our UX writers ✨

2025-01-16 14:40 UTC, j-mnizhek commented on semcore/bulk-textarea/src/translations/en.json
> +  "BulkTextarea.Counter.ofAllowedRows:sr-message": "of {rowsNumber} allowed rows",
```suggestion
  "BulkTextarea.Counter.ofAllowedRows:sr-message": "of {rowsNumber} rows",
```

2025-01-16 14:40 UTC, j-mnizhek commented on semcore/bulk-textarea/src/translations/en.json
> +  "BulkTextarea.Counter.limitReached:sr-message": "Limit is almost reached",
```suggestion
  "BulkTextarea.Counter.limitReached:sr-message": "Limit reached",
```

2025-01-16 14:40 UTC, j-mnizhek commented on semcore/bulk-textarea/src/translations/en.json
> +  "BulkTextarea.Counter.limitExceeded:sr-message": "Limit is exceeded",
```suggestion
  "BulkTextarea.Counter.limitExceeded:sr-message": "Limit exceeded",
```

2025-01-16 14:40 UTC, j-mnizhek commented on semcore/bulk-textarea/src/translations/en.json
> +  "BulkTextarea.ErrorsNavigation.selectedError": "{errorIndex} out of {errorsCount}",
```suggestion
  "BulkTextarea.ErrorsNavigation.selectedError": "Error {errorIndex} out of {errorsCount}",
```

2025-01-16 14:40 UTC, j-mnizhek commented on semcore/bulk-textarea/src/translations/en.json
> +  "BulkTextarea.ErrorsNavigation.nextError:aria-label": "Go to the {index, selectordinal, one {#st} two {#nd} few {#rd} other {#th}} invalid value"
Let's simplify this a little bit according to our UX writers recommendations. Let's rename buttons to "Previous error" and "Next error".

<img width="961" alt="image" src="https://github.com/user-attachments/assets/0e2983b2-9492-4e99-a282-386a86b3ede3" />

2025-01-16 18:07 UTC, j-mnizhek commented
Gathered documentation for the component in this https://github.com/semrush/intergalactic/pull/1918 😎

_As soon our component will be ready for release, I'll double check it and remove some comments there._

2025-01-28 15:49 UTC, sheila-semrush commented on website/docs/components/bulk-textarea/bulk-textarea.md
> +![](static/bulktextarea-composition.png)
shifted a bit
<img width="396" alt="image" src="https://github.com/user-attachments/assets/da519bae-f4d7-4e6e-8b8f-057036a751dd" />

2025-01-28 16:04 UTC, sheila-semrush commented on semcore/bulk-textarea/src/BulkTextarea.tsx
> +  ClearAllButton,
wouldn't it be better to name it "ClearAll" without "Button"? We have a lot of components named like "CloseIcon", and it doesn't look good now that we've replaced icons with buttons. Even if Button is unlikely to change, it might be safer not to specify anything we don't have to specify

2025-01-28 16:16 UTC, sheila-semrush commented on website/docs/components/bulk-textarea/bulk-textarea.md
> +| M (`--fs-200`)   | ![](static/bulk-m.png) |
some thoughts about alts for illustrations
we'll have to return to his page again in the task about alt texts, so why not do it right from the start
I don't like the idea of useless alts ("example of textarea of size L"), and empty alt isn't good either in this case, because it creates an empty cell for SR
I tried restructuring this table into a bullet list, or merging columns, but it doesn't look good

so I have another idea
what if we do something like this:
<img width="431" alt="image" src="https://github.com/user-attachments/assets/f7fcf471-95ac-440f-92c9-3c3da479e3a1" />
this way we also fix another problem — different sizes scaled unconsistently on different illustrations, on one illustration all sizes will look correctly relative to each other

2025-01-28 16:33 UTC, sheila-semrush commented on website/docs/components/bulk-textarea/bulk-textarea.md
> +### Rows
I think it should be called "lines" in docs and in component/prop names, left a message in chat to discuss

2025-01-28 16:38 UTC, sheila-semrush commented on website/docs/components/bulk-textarea/bulk-textarea.md
> +### Clear field button
```suggestion
### Clear all button
```
?

2025-01-28 16:40 UTC, sheila-semrush commented on website/docs/components/bulk-textarea/bulk-textarea.md
> +Rows with values that exceed the limit are highlighted. Counter changes its theme to `danger`.
```suggestion
Lines that exceed the limit are highlighted. Counter changes its theme to `danger`.
```
values as well

2025-01-28 16:45 UTC, sheila-semrush commented on website/docs/components/bulk-textarea/bulk-textarea.md
> +When a button is clicked, the cursor moves to the first or last invalid row, depending on the button. The entire row's value is selected for quick deletion. The text next to the navigation buttons up
```suggestion
When a button is pressed, the cursor moves to the first or last invalid row, depending on the button. The entire row's value is selected for quick deletion. The text next to the navigation buttons updates to _"n out of n"_ when the cursor is moved using the buttons, keyboard, or mouse.
```
a bit more inclusive, I think

2025-01-28 17:05 UTC, sheila-semrush commented on website/docs/components/bulk-textarea/bulk-textarea-a11y.md
> +| `BulkTextarea.InputField > div > p`            | `aria-invalid="true"`                                    | A row gets this property when it gets the `invalid` status.
so InputField.Row component exists only in design docs/figma? :(

2025-01-28 17:11 UTC, sheila-semrush commented on stories/components/bulk-textarea/docs/examples/BaseExample.tsx
@Valeria-Zimnitskaya can we rename it to "basic-usage" for consistency? It will be easier to find

2025-01-28 17:13 UTC, sheila-semrush commented on semcore/bulk-textarea/src/BulkTextarea.types.ts
> +  ofRows?: InputFieldProps['ofRows'];
is this the max number of lines (values)? wouldn't it be clearer to call it "maxLines" or "maxValues"?

2025-01-28 17:20 UTC, sheila-semrush requested changes
left some suggestions

2025-01-28 17:22 UTC, sheila-semrush commented on website/docs/components/bulk-textarea/bulk-textarea.md
> +When the number of values reaches the limit, the counter changes its theme to `warning`.
(orrr maybe not, I'm not 100% sure, for me "values" is at least clearer than "rows", but I like "lines" most of course)

2025-01-29 06:45 UTC, ilyabrower commented on semcore/bulk-textarea/src/BulkTextarea.tsx
> +  ClearAllButton,
agree, changed

2025-01-29 06:58 UTC, ilyabrower commented on semcore/bulk-textarea/src/BulkTextarea.types.ts
> +  ofRows?: InputFieldProps['ofRows'];
changed to maxLiens

2025-01-29 07:02 UTC, ilyabrower commented on website/docs/components/bulk-textarea/bulk-textarea-a11y.md
> +|                                                | `aria-errormessage="[Your message here]"`                | Identifies the element that provides an error message for the .
I changed it to data-errormessage, we don't use it for VO. So, let's just remove it from here

2025-01-29 07:37 UTC, Valeria-Zimnitskaya commented on stories/components/bulk-textarea/docs/examples/BaseExample.tsx
done

2025-01-29 10:09 UTC, j-mnizhek commented on website/docs/components/bulk-textarea/bulk-textarea-a11y.md
> +|                                                | `aria-describedby="IDREF"`                               | Gives the item an accessible description by referring to the `aria-errormessage`, the too
When there is an error in a field, it will get a tooltip with the error text, which is linked to the field via `aria-describedby`
<img width="711" alt="image" src="https://github.com/user-attachments/assets/5e6918c9-f9ed-4315-b669-959596784503" />

2025-01-29 10:17 UTC, j-mnizhek commented on website/docs/components/bulk-textarea/bulk-textarea-a11y.md
> +|                                                | `aria-errormessage="[Your message here]"`                | Identifies the element that provides an error message for the .
I wouldn't remove it from the table, would just change it to:

> |   | `data-errormessage="Your message here"`  | Adds an error message for a line with `invalid` state.  |

2025-01-30 10:53 UTC, Valeria-Zimnitskaya approved these changes

2025-01-30 11:46 UTC, sheila-semrush commented on semcore/bulk-textarea/src/translations/en.json
> +  "BulkTextarea.Counter.ofAllowedRows:sr-message": "of {rowsNumber} rows",
```suggestion
  "BulkTextarea.Counter.ofAllowedRows:sr-message": "of {rowsNumber} lines",
```
we should probably replace rows with lines here too (and update translations of this string)

2025-01-30 11:55 UTC, sheila-semrush commented on website/docs/components/bulk-textarea/bulk-textarea-a11y.md
> +|                                                | `aria-describedby="IDREF"`                               | Gives the item an accessible description by referring to the `aria-errormessage`, the too
```suggestion
|                                                | `aria-describedby="IDREF"`                               | Gives the item an accessible description. In invalid state, refers to the error message. |
```
what do you think?

2025-01-30 14:11 UTC, j-mnizhek approved these changes
Made last small updates to the design and a11y documentation, and have no other comments so far. Really cool component we got now ✨ Folks, @ilyabrower @Valeria-Zimnitskaya , you are great ❤️

2025-01-30 14:36 UTC, j-mnizhek commented on semcore/bulk-textarea/src/translations/en.json
> +  "BulkTextarea.Counter.ofAllowedRows:sr-message": "of {rowsNumber} lines",
I was thinking, since we count values not lines in the counter, shouldn't we use not "lines", but some other word here? Or maybe remove this word completely.

2025-01-30 14:37 UTC, j-mnizhek commented on semcore/bulk-textarea/src/translations/en.json
> +  "BulkTextarea.Counter.ofAllowedRows:sr-message": "of {rowsNumber} lines",
I was thinking, since we count values not lines in the counter, shouldn't we use not "lines", but some other word here? Or maybe remove this word completely.

2025-01-31 13:45 UTC, sheila-semrush approved these changes
yay, let's go!

2025-01-31 14:31 UTC, merged