[utils] Added a check for empty children for `addonTextChildren` func…
semrush/intergalactic pull request #400
Opened 2022-09-29 14:06 UTC by ekrasnopolskaia

…tion

## Description

In some components there is an extra indent in the absence of children
Too little change for a detailed description

2022-09-29 14:35 UTC, phytonmk approved these changes

2022-09-29 16:00 UTC, freeyoungstrong approved these changes

2022-09-29 20:48 UTC, phytonmk requested changes
I have rebased and actualized the branch but as I see unit tests helped us to spot that in some cases proposed changes may break user apps.

2022-10-03 12:50 UTC, lsroman reviewed
I would like to discuss again why change addonTextChildren in the DatePPicker

2022-10-03 12:50 UTC, lsroman commented on semcore/button/package.json
> +    "@semcore/icon": "^2.16"
It should be in devDependencies

2022-10-03 12:50 UTC, lsroman commented on semcore/link/__tests__/index.test.tsx
> +import CheckM from '@semcore/icon/Check/m';
This should be added to devDependencies

2022-10-03 12:50 UTC, lsroman commented on semcore/date-picker/src/components/ButtonTrigger.jsx
> +      {addonText(Children, ButtonTrigger.Text, ButtonTrigger.Addon)}
This code is not working correctly. See what the "addonText" function accepts

2022-10-04 13:38 UTC, merged